Public Class EmailAllProductandTransactionDocs

  'Scenario: Sends an email after processing a sales invoice, including all documents in product's document store, as well as standard transactional documents
  'Prerequisities: None  
  'Breakpoint: AfterSalesInvoiceProcess	
	
  Public Sub Invoke(ByVal transaction As Sybiz.Vision.Platform.Debtors.Transaction.SalesInvoice, ByVal e As Sybiz.Vision.Platform.Admin.Breakpoints.BreakpointEventArgs) 'Do not remove - SYBIZ

    Dim attachmentList As New List(Of Byte())
    Dim fileNameList As New List(Of String)
			
    For Each line As Sybiz.Vision.Platform.Debtors.Transaction.SalesInvoiceLine In transaction.Lines
      If line.AccountType = SalesLineType.IC Then
        Dim product As Sybiz.Vision.Platform.Inventory.Product = Sybiz.Vision.Platform.Inventory.Product.GetObject(line.Account)
        If product.DocumentsExist = True Then
          For Each document As Sybiz.Vision.Platform.Common.DocumentStore In product.Documents
            attachmentList.Add(document.Document)
            fileNameList.Add(document.FileName)
          Next
        End If
      End If
    Next
			
    Dim transactionDocuments As List(Of Byte()) = BreakpointHelpers.CreateTransactionDocuments(TransactionType.SalesInvoice, transaction.Id)
			
    Dim templateCount As Integer = 1
			
    For each template As Byte() In transactionDocuments
      attachmentList.Add(template)
      fileNameList.Add(transaction.TransactionNumber & " " & templateCount & ".pdf")
      templateCount += 1
    Next
			
    BreakpointHelpers.SendEmail("breakpointtest@sybiz.com", Nothing, Nothing, "BREAKPOINT", "GENERATED BY BREAKPOINT", fileNameList, attachmentList)
	
  End Sub

End Class
