Public Class EmailAllProductandTransactionDocs

  'Scenario: Sends an email after processing a sales invoice, including all documents in product's document store, as well as standard transactional documents
  'Prerequisities: None  
  'Breakpoint: AfterSalesInvoiceProcess	
	
  Public Sub Invoke(ByVal transaction As Sybiz.Vision.Platform.Debtors.Transaction.SalesInvoice, ByVal e As Sybiz.Vision.Platform.Admin.Breakpoints.BreakpointEventArgs) 'Do not remove - SYBIZ

    Dim attachments As New List(Of Byte())
    Dim filenames As New List(Of String)
			
    For Each line As Sybiz.Vision.Platform.Debtors.Transaction.SalesInvoiceLine In transaction.Lines
      If line.AccountType = SalesLineType.IC Then
        Dim p As Sybiz.Vision.Platform.Inventory.Product = Sybiz.Vision.Platform.Inventory.Product.GetObject(line.Account)
        If p.DocumentsExist = True Then
          For Each doc As Sybiz.Vision.Platform.Common.DocumentStore In p.Documents
            attachments.Add(doc.Document)
            filenames.Add(doc.FileName)
          Next
        End If
      End If
    Next
			
    Dim transactiondocuments As List(Of Byte()) = BreakpointHelpers.CreateTransactionDocuments(TransactionType.SalesInvoice, transaction.Id)
			
    Dim templatecount As Integer = 1
			
    For each template As Byte() In transactiondocuments
      attachments.Add(template)
      filenames.Add(transaction.TransactionNumber & " " & templatecount & ".pdf")
      templatecount += 1
    Next
			
    BreakpointHelpers.SendEmail("breakpointtest@sybiz.com", Nothing, Nothing, "BREAKPOINT", "GENERATED BY BREAKPOINT", filenames, attachments)
	
  End Sub

End Class
